
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class simulation extends javax.swing.JFrame implements Runnable  {

    Thread t;
    
    JButton[] button_array;
    int[] A;
    int choice; 
    
    
    
    /**
     * Creates new form simulation
     */
    public simulation() {
        initComponents();
          t = new Thread(this);
           jLabel2.setVisible(false);
           jLabel1.setVisible(false);
           
      jButton2.setVisible(false);
      jButton3.setVisible(false);
      jButton4.setVisible(false);
      jButton5.setVisible(false);
      jButton6.setVisible(false);
      jButton7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setMaximumSize(new java.awt.Dimension(79, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(35, 22));

        jTextField2.setMinimumSize(new java.awt.Dimension(35, 22));

        jTextField3.setMinimumSize(new java.awt.Dimension(35, 22));

        jTextField4.setMinimumSize(new java.awt.Dimension(35, 22));

        jTextField5.setMinimumSize(new java.awt.Dimension(35, 22));

        jTextField6.setMinimumSize(new java.awt.Dimension(35, 22));

        jButton2.setMinimumSize(new java.awt.Dimension(35, 22));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 25));

        jButton3.setMinimumSize(new java.awt.Dimension(35, 22));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 25));

        jButton4.setMinimumSize(new java.awt.Dimension(35, 22));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 25));

        jButton5.setMinimumSize(new java.awt.Dimension(35, 22));
        jButton5.setPreferredSize(new java.awt.Dimension(50, 25));

        jButton6.setMinimumSize(new java.awt.Dimension(35, 22));
        jButton6.setPreferredSize(new java.awt.Dimension(50, 25));

        jButton7.setMinimumSize(new java.awt.Dimension(35, 22));
        jButton7.setPreferredSize(new java.awt.Dimension(50, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Bubble Sort", "Quick Sort" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton8.setText("Time Complexity");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         A = new int[6];
    
    if(jTextField1.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Insert a number", "Warning", 2);
        jTextField1.grabFocus();
    }
    else if(jTextField2.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Insert a number", "Warning", 2);
        jTextField2.grabFocus();
    }
    else if(jTextField3.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Insert a number", "Warning", 2);
        jTextField3.grabFocus();
    }
    else if(jTextField4.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Insert a number", "Warning", 2);
        jTextField4.grabFocus();
    }
      else if(jTextField5.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Insert a number", "Warning", 2);
        jTextField5.grabFocus();
    }
      else if(jTextField6.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Insert a number", "Warning", 2);
        jTextField6.grabFocus();
    }
    
      else{
      A[0]=Integer.parseInt(jTextField1.getText());
      A[1]=Integer.parseInt(jTextField2.getText());
      A[2]=Integer.parseInt(jTextField3.getText());
      A[3]=Integer.parseInt(jTextField4.getText());
      A[4]=Integer.parseInt(jTextField5.getText());
      A[5]=Integer.parseInt(jTextField6.getText());
      
      for(int k=0; k<A.length; k++){System.out.println(A[k]);}
      
      jButton2.setVisible(true);
      jButton3.setVisible(true);
      jButton4.setVisible(true);
      jButton5.setVisible(true);
      jButton6.setVisible(true);
      jButton7.setVisible(true);
      
      jButton2.setText(jTextField1.getText());
      jButton3.setText(jTextField2.getText());
      jButton4.setText(jTextField3.getText());
      jButton5.setText(jTextField4.getText());
      jButton6.setText(jTextField5.getText());
      jButton7.setText(jTextField6.getText());
      
      button_array = new JButton[]{jButton2,jButton3,jButton4,jButton5,jButton6,jButton7};
      
     
      t.start();

    }                                        
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
                choice = jComboBox1.getSelectedIndex();
        System.out.println("choice = "+choice);
        System.out.println("Elements before Sorting");
    }                                          

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
            
      jButton2.setText(Integer.toString(A[0]));
      jButton3.setText(Integer.toString(A[1]));
      jButton4.setText(Integer.toString(A[2]));
      jButton5.setText(Integer.toString(A[3]));
      jButton6.setText(Integer.toString(A[4]));
      jButton7.setText(Integer.toString(A[5]));
         Random rd = new Random(); // creating Random object
       int no=Integer.parseInt(jTextField7.getText());
       jLabel2.setVisible(true);
       jLabel1.setVisible(true);
       jLabel1.setText("Generated " + no +" random numbers.");
       System.out.println("Generated " + no +" random numbers.");
      int[] arr = new int[no];
         
      for (int i = 0; i < arr.length; i++) {
         arr[i] = rd.nextInt();
      }
        if(choice==1){
        long startTime = System.currentTimeMillis();
        bubble(arr);
      long endTime = System.currentTimeMillis();

      
long time = endTime - startTime;

jLabel2.setText("Time taken to sort using Bubble Sort = "+time+" milliseconds");
System.out.println("Time taken to sort using Bubble Sort = "+time+" milliseconds");


       }
        
        if(choice==2){
        long startTime = System.currentTimeMillis();
        qS(arr,0, arr.length-1);
      long endTime = System.currentTimeMillis();

      
long time = endTime - startTime;

System.out.println("Time taken to sort using Quick Sort = "+time+" milliseconds");

jLabel2.setText("Time taken to sort using Quick Sort = "+time+" milliseconds");
        
    }                                        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simulation().setVisible(true);
            }
        });
    }

    
        public void run(){
       
        if(choice==1)
        {   
            
            System.out.println("Starting Bubble Sort");
        int i,j,n,temp;
        n= A.length;
       
        for(i=0; i<n; i++){
            
            for(j=0; j<(n-i); j++){
              try{  if(A[j] > A[j+1])
                { 
                    temp = A[j];
                    A[j]=A[j+1];
                    A[j+1]=temp;
                
                    try{
                        swap2(j, j+1);
                    }
                    catch(InterruptedException e){System.out.println("error");}
                }
            }
            catch(Exception e){//System.out.println("error-errow..!!");}
            }}
            
        }
        for(int k=0; k<A.length; k++){System.out.println(A[k]);}
        
     }
        
        
        if(choice == 2){ 
            System.out.println("Starting Quick Sort");
            quickSort(A,0,A.length-1);
        for(int k=0; k<A.length; k++){System.out.println(A[k]);}
     }
        
 }
    
    
    public void bubble(int A[]){
int i,j,n,temp;
        n= A.length-1;   
        for(i=0; i<n; i++){
            
            for(j=0; j<(n-i); j++){
                if(A[j] > A[j+1])
                { 
                    temp = A[j];
                    A[j]=A[j+1];
                    A[j+1]=temp;
                
                }
            
            
            }
            
        }
    }
        
    public int parttt (int arr[], int low,int  high)
{
    // pivot (Element to be placed at right position)
   int pivot = arr[high];  
 int temp;
int    i = (low - 1);  // Index of smaller element

    for (int j = low; j <= high- 1; j++)
    {
        // If current element is smaller than the pivot
        if (arr[j] < pivot)
        {
            i++;    // increment index of smaller element
            //swap arr[i] and arr[j]
            try{
                        swap2(i, j);
                    }
                    catch(InterruptedException e){System.out.println("error");}
            temp = arr[i];
            arr[i]=arr[j];
            arr[j]=temp;
             
        }
    }
    //swap arr[i + 1] and arr[high])
     try{
                        swap2(i+1, high);
                    }
                    catch(InterruptedException e){System.out.println("error");}


    temp = arr[i+1];
    arr[i+1]=arr[high];
    arr[high]=temp;

    return (i + 1);
}
        
 public void quickSort(int a[], int beg, int end)  
    {  
          
        int loc;  
        if(beg<end)  
        {  
            loc = parttt(a, beg, end);
            quickSort(a, beg, loc-1);  
            quickSort(a, loc+1, end);  
        }  
    }  
 public void qS(int a[], int beg, int end)  
    {  

        int loc;  
        if(beg<end)  
        {  
            loc = part(a, beg, end);
            qS(a, beg, loc-1);  
            qS(a, loc+1, end);  
        }  
    } 
    public int part(int a[], int beg, int end)  
    {  
          
        int left, right, temp, loc, flag;     
        loc = left = beg;  
        right = end;  
        flag = 0;  
        while(flag != 1)  
        {  
            while((a[loc] <= a[right]) && (loc!=right))  
            right--;  
            if(loc==right)  
            flag =1;  
            if(a[loc]>a[right])  
            {           
                temp = a[loc];  
                a[loc] = a[right];  
                a[right] = temp;  
                loc = right;  
            }  
            if(flag!=1)  
            {  
                while((a[loc] >= a[left]) && (loc!=left))  
                left++;  
                if(loc==left)  
                flag =1;  
                if(a[loc] <a[left])  
                {  
                    temp = a[loc];  
                    a[loc] = a[left];  
                    a[left] = temp; 
                    loc = left;  
                }  
            }  
        }  
        return loc;  
    }  
   
    
    
    public void swap2(int num1, int num2) throws InterruptedException{
  
   for(int i=0; i<30;i++){
        button_array[num1].setLocation(button_array[num1].getLocation().x, button_array[num1].getLocation().y+1);
       
        button_array[num2].setLocation(button_array[num2].getLocation().x, button_array[num2].getLocation().y-1);
       t.sleep(10);
   }
   
   int len = button_array[num2].getX()- button_array[num1].getX();
   
   for (int i=0;i<len;i++){
   button_array[num1].setLocation(button_array[num1].getLocation().x+1, button_array[num1].getLocation().y);
       
        button_array[num2].setLocation(button_array[num2].getLocation().x-1, button_array[num2].getLocation().y);
        t.sleep(10);
   }
    for (int i=0;i<30;i++){
   button_array[num1].setLocation(button_array[num1].getLocation().x, button_array[num1].getLocation().y-1);
       
        button_array[num2].setLocation(button_array[num2].getLocation().x, button_array[num2].getLocation().y+1);
        t.sleep(10);
   }
    
    JButton temp = button_array[num1];
    button_array[num1] = button_array[num2];
    button_array[num2] = temp;
    t.sleep(10);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration                   
}
